import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import AppHeader from "@/layout/AppHeader";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  weight: ["400"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={urbanist.className}>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full relative flex flex-col">
            {/* <SidebarTrigger /> */}
            
              <AppHeader />
            
                {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
